
image: wendo/mpi

#variables:
#    GIT_SUBMODULE_STRATEGY: normal

before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive

stages:
    - test

test_sct_debug_job:
    stage: test
    script:
        - ./cmake.bash Debug -D MEFDN_ENABLE_MEULT=OFF -D MEDSM2_ULT_ITF=SCT
        - ./make.bash Debug VERBOSE=1
        - ./ctest.bash Debug -V

test_sct_relwithdebinfo_job:
    stage: test
    script:
        - ./cmake.bash RelWithDebInfo -D MEFDN_ENABLE_MEULT=OFF -D MEDSM2_ULT_ITF=SCT
        - ./make.bash RelWithDebInfo VERBOSE=1
        - ./ctest.bash RelWithDebInfo -V

test_sct_release_job:
    stage: test
    script:
        - ./cmake.bash Release -D MEFDN_ENABLE_MEULT=OFF -D MEDSM2_ULT_ITF=SCT
        - ./make.bash Release VERBOSE=1
        - ./ctest.bash Release -V


test_ctmth_debug_job:
    stage: test
    script:
        - ./cmake.bash Debug -D MEFDN_ENABLE_MEULT=OFF -D MEDSM2_ULT_ITF=CTMTH
        - ./make.bash Debug VERBOSE=1
        - ./ctest.bash Debug -V

test_ctmth_relwithdebinfo_job:
    stage: test
    script:
        - ./cmake.bash RelWithDebInfo -D MEFDN_ENABLE_MEULT=OFF -D MEDSM2_ULT_ITF=CTMTH
        - ./make.bash RelWithDebInfo VERBOSE=1
        - ./ctest.bash RelWithDebInfo -V

test_ctmth_release_job:
    stage: test
    script:
        - ./cmake.bash Release -D MEFDN_ENABLE_MEULT=OFF -D MEDSM2_ULT_ITF=CTMTH
        - ./make.bash Release VERBOSE=1
        - ./ctest.bash Release -V


#test_smth_debug_job:
#    stage: test
#    script:
#        - ./cmake.bash Debug -D MEFDN_ENABLE_MEULT=OFF
#        - ./make.bash Debug VERBOSE=1
#        - ./ctest.bash Debug -V
#
#test_smth_relwithdebinfo_job:
#    stage: test
#    script:
#        - ./cmake.bash RelWithDebInfo -D MEFDN_ENABLE_MEULT=OFF
#        - ./make.bash RelWithDebInfo VERBOSE=1
#        - ./ctest.bash RelWithDebInfo -V
#
#test_smth_release_job:
#    stage: test
#    script:
#        - ./cmake.bash Release -D MEFDN_ENABLE_MEULT=OFF
#        - ./make.bash Release VERBOSE=1
#        - ./ctest.bash Release -V

test_myth_debug_job:
    stage: test
    script:
        - ./cmake.bash Debug
        - ./make.bash Debug VERBOSE=1
        - ./ctest.bash Debug -V

test_myth_relwithdebinfo_job:
    stage: test
    script:
        - ./cmake.bash RelWithDebInfo
        - ./make.bash RelWithDebInfo VERBOSE=1
        - ./ctest.bash RelWithDebInfo -V

test_myth_release_job:
    stage: test
    script:
        - ./cmake.bash Release
        - ./make.bash Release VERBOSE=1
        - ./ctest.bash Release -V


