
image: wendo/mpi

#variables:
#    GIT_SUBMODULE_STRATEGY: normal

before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive

stages:
    - test

test_smth_debug_job:
    stage: test
    script:
        - ./cmake.sh Debug -D MEFDN_ENABLE_MEULT=OFF
        - ./make.sh Debug VERBOSE=1
        - ./ctest.sh Debug -V

test_smth_relwithdebinfo_job:
    stage: test
    script:
        - ./cmake.sh RelWithDebInfo -D MEFDN_ENABLE_MEULT=OFF
        - ./make.sh RelWithDebInfo VERBOSE=1
        - ./ctest.sh RelWithDebInfo -V

test_smth_release_job:
    stage: test
    script:
        - ./cmake.sh Release -D MEFDN_ENABLE_MEULT=OFF
        - ./make.sh Release VERBOSE=1
        - ./ctest.sh Release -V

test_myth_debug_job:
    stage: test
    script:
        - ./cmake.sh Debug
        - ./make.sh Debug VERBOSE=1
        - ./ctest.sh Debug -V

test_myth_relwithdebinfo_job:
    stage: test
    script:
        - ./cmake.sh RelWithDebInfo
        - ./make.sh RelWithDebInfo VERBOSE=1
        - ./ctest.sh RelWithDebInfo -V

test_myth_release_job:
    stage: test
    script:
        - ./cmake.sh Release
        - ./make.sh Release VERBOSE=1
        - ./ctest.sh Release -V


