
image: wendo/mpich

#variables:
#    GIT_SUBMODULE_STRATEGY: normal

before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive

stages:
    - test

# SCT

test_sct_debug_job:
    stage: test
    script:
        - ./cmake.bash Debug -D MEDSM2_ULT_ITF=SCT
        - ./make.bash Debug VERBOSE=1 -j 8
        - ./ctest.bash Debug -V

test_sct_relwithdebinfo_job:
    stage: test
    script:
        - ./cmake.bash RelWithDebInfo -D MEDSM2_ULT_ITF=SCT
        - ./make.bash RelWithDebInfo VERBOSE=1 -j 8
        - ./ctest.bash RelWithDebInfo -V

test_sct_release_job:
    stage: test
    script:
        - ./cmake.bash Release -D MEDSM2_ULT_ITF=SCT
        - ./make.bash Release VERBOSE=1 -j 8
        - ./ctest.bash Release -V

# CTMTH

test_ctmth_debug_job:
    stage: test
    script:
        - ./cmake.bash Debug -D MEDSM2_ULT_ITF=CTMTH
        - ./make.bash Debug VERBOSE=1 -j 8
        - ./ctest.bash Debug -V

test_ctmth_relwithdebinfo_job:
    stage: test
    script:
        - ./cmake.bash RelWithDebInfo -D MEDSM2_ULT_ITF=CTMTH
        - ./make.bash RelWithDebInfo VERBOSE=1 -j 8
        - ./ctest.bash RelWithDebInfo -V

test_ctmth_release_job:
    stage: test
    script:
        - ./cmake.bash Release -D MEDSM2_ULT_ITF=CTMTH
        - ./make.bash Release VERBOSE=1 -j 8
        - ./ctest.bash Release -V

# MTH

test_mth_debug_job:
    stage: test
    script:
        - ./cmake.bash Debug -D MEDSM2_ULT_ITF=MTH
        - ./make.bash Debug VERBOSE=1 -j 8
        - ./ctest.bash Debug -V

test_mth_relwithdebinfo_job:
    stage: test
    script:
        - ./cmake.bash RelWithDebInfo -D MEDSM2_ULT_ITF=MTH
        - ./make.bash RelWithDebInfo VERBOSE=1 -j 8
        - ./ctest.bash RelWithDebInfo -V

test_mth_release_job:
    stage: test
    script:
        - ./cmake.bash Release -D MEDSM2_ULT_ITF=MTH
        - ./make.bash Release VERBOSE=1 -j 8
        - ./ctest.bash Release -V

# OpenMPI

test_openmpi_sct_relwithdebinfo_job:
    stage: test
    image: wendo/openmpi
    script:
        - ./cmake.bash RelWithDebInfo -D MEDSM2_ULT_ITF=SCT
        - ./make.bash RelWithDebInfo VERBOSE=1 -j 8
        - ./ctest.bash RelWithDebInfo -V

test_openmpi_ctmth_relwithdebinfo_job:
    stage: test
    image: wendo/openmpi
    script:
        - ./cmake.bash RelWithDebInfo -D MEDSM2_ULT_ITF=CTMTH
        - ./make.bash RelWithDebInfo VERBOSE=1 -j 8
        - ./ctest.bash RelWithDebInfo -V

test_openmpi_mth_relwithdebinfo_job:
    stage: test
    image: wendo/openmpi
    script:
        - ./cmake.bash RelWithDebInfo -D MEDSM2_ULT_ITF=MTH
        - ./make.bash RelWithDebInfo VERBOSE=1 -j 8
        - ./ctest.bash RelWithDebInfo -V

# medsm2 with dir,fixed

test_nofastrel_mth_relwithdebinfo_job:
    stage: test
    script:
        - ./cmake.bash RelWithDebInfo -D MEDSM2_ULT_ITF=MTH -D MEDSM2_ENABLE_FAST_RELEASE=OFF
        - ./make.bash RelWithDebInfo VERBOSE=1 -j 8
        - ./ctest.bash RelWithDebInfo -V

test_nolazymerge_mth_relwithdebinfo_job:
    stage: test
    script:
        - ./cmake.bash RelWithDebInfo -D MEDSM2_ULT_ITF=MTH -D MEDSM2_ENABLE_FAST_RELEASE=OFF -D MEDSM2_ENABLE_LAZY_MERGE=OFF
        - ./make.bash RelWithDebInfo VERBOSE=1 -j 8
        - ./ctest.bash RelWithDebInfo -V

test_dir_mth_relwithdebinfo_job:
    stage: test
    script:
        - ./cmake.bash RelWithDebInfo -D MEDSM2_ULT_ITF=MTH -D MEDSM2_ENABLE_FAST_RELEASE=OFF -D MEDSM2_ENABLE_LAZY_MERGE=OFF -D MEDSM2_USE_DIRECTORY_COHERENCE=ON
        - ./make.bash RelWithDebInfo VERBOSE=1 -j 8
        - ./ctest.bash RelWithDebInfo -V

test_fixed_mth_relwithdebinfo_job:
    stage: test
    script:
        - ./cmake.bash RelWithDebInfo -D MEDSM2_ULT_ITF=MTH -D MEDSM2_ENABLE_FAST_RELEASE=OFF -D MEDSM2_ENABLE_LAZY_MERGE=OFF -D MEDSM2_ENABLE_MIGRATION=OFF
        - ./make.bash RelWithDebInfo VERBOSE=1 -j 8
        - ./ctest.bash RelWithDebInfo -V

test_dir_fixed_mth_relwithdebinfo_job:
    stage: test
    script:
        - ./cmake.bash RelWithDebInfo -D MEDSM2_ULT_ITF=MTH -D MEDSM2_ENABLE_FAST_RELEASE=OFF -D MEDSM2_ENABLE_LAZY_MERGE=OFF -D MEDSM2_USE_DIRECTORY_COHERENCE=ON -D MEDSM2_ENABLE_MIGRATION=OFF
        - ./make.bash RelWithDebInfo VERBOSE=1 -j 8
        - ./ctest.bash RelWithDebInfo -V

# medsm3

test_medsm3_mth_relwithdebinfo_job:
    stage: test
    script:
        - ./cmake.bash RelWithDebInfo -D MEDSM2_ULT_ITF=MTH -D MEOMP_ENABLE_MEDSM3=ON
        - ./make.bash RelWithDebInfo VERBOSE=1 -j 8
        - ./ctest.bash RelWithDebInfo -V

test_medsm3_nofastrel_mth_relwithdebinfo_dir_job:
    stage: test
    script:
        - ./cmake.bash RelWithDebInfo -D MEDSM2_ULT_ITF=MTH -D MEOMP_ENABLE_MEDSM3=ON -D MEDSM2_ENABLE_FAST_RELEASE=OFF
        - ./make.bash RelWithDebInfo VERBOSE=1 -j 8
        - ./ctest.bash RelWithDebInfo -V

test_medsm3_nolazymerge_mth_relwithdebinfo_dir_job:
    stage: test
    script:
        - ./cmake.bash RelWithDebInfo -D MEDSM2_ULT_ITF=MTH -D MEOMP_ENABLE_MEDSM3=ON -D MEDSM2_ENABLE_FAST_RELEASE=OFF -D MEDSM2_ENABLE_LAZY_MERGE=OFF
        - ./make.bash RelWithDebInfo VERBOSE=1 -j 8
        - ./ctest.bash RelWithDebInfo -V

test_medsm3_dir_mth_relwithdebinfo_dir_job:
    stage: test
    script:
        - ./cmake.bash RelWithDebInfo -D MEDSM2_ULT_ITF=MTH -D MEOMP_ENABLE_MEDSM3=ON -D MEDSM2_ENABLE_FAST_RELEASE=OFF -D MEDSM2_ENABLE_LAZY_MERGE=OFF -D MEDSM2_USE_DIRECTORY_COHERENCE=ON
        - ./make.bash RelWithDebInfo VERBOSE=1 -j 8
        - ./ctest.bash RelWithDebInfo -V

test_medsm3_fixed_mth_relwithdebinfo_dir_job:
    stage: test
    script:
        - ./cmake.bash RelWithDebInfo -D MEDSM2_ULT_ITF=MTH -D MEOMP_ENABLE_MEDSM3=ON -D MEDSM2_ENABLE_FAST_RELEASE=OFF -D MEDSM2_ENABLE_LAZY_MERGE=OFF -D MEDSM2_ENABLE_MIGRATION=OFF
        - ./make.bash RelWithDebInfo VERBOSE=1 -j 8
        - ./ctest.bash RelWithDebInfo -V

test_medsm3_dir_fixed_mth_relwithdebinfo_dir_job:
    stage: test
    script:
        - ./cmake.bash RelWithDebInfo -D MEDSM2_ULT_ITF=MTH -D MEOMP_ENABLE_MEDSM3=ON -D MEDSM2_ENABLE_FAST_RELEASE=OFF -D MEDSM2_ENABLE_LAZY_MERGE=OFF -D MEDSM2_USE_DIRECTORY_COHERENCE=ON -D MEDSM2_ENABLE_MIGRATION=OFF
        - ./make.bash RelWithDebInfo VERBOSE=1 -j 8
        - ./ctest.bash RelWithDebInfo -V


# UCT

compile_uct_debug_job:
    stage: test
    script:
        - ./cmake.bash Debug -D MEDSM2_RMA_ITF=UCT -D MEDSM2_ULT_ITF=SCT
        - ./make.bash Debug VERBOSE=1 -j 8
        - ./cmake.bash Debug -D MEDSM2_RMA_ITF=UCT -D MEDSM2_ULT_ITF=CTMTH
        - ./make.bash Debug VERBOSE=1 -j 8
        - ./cmake.bash Debug -D MEDSM2_RMA_ITF=UCT -D MEDSM2_ULT_ITF=MTH
        - ./make.bash Debug VERBOSE=1 -j 8


