
image: wendo/mpi

#variables:
#    GIT_SUBMODULE_STRATEGY: normal

before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive

stages:
    - test

# SCT

test_sct_debug_job:
    stage: test
    script:
        - ./cmake.bash Debug -D MEFDN_ENABLE_MEULT=OFF -D MEDSM2_ULT_ITF=SCT
        - ./make.bash Debug VERBOSE=1
        - ./ctest.bash Debug -V

test_sct_relwithdebinfo_job:
    stage: test
    script:
        - ./cmake.bash RelWithDebInfo -D MEFDN_ENABLE_MEULT=OFF -D MEDSM2_ULT_ITF=SCT
        - ./make.bash RelWithDebInfo VERBOSE=1
        - ./ctest.bash RelWithDebInfo -V

test_sct_release_job:
    stage: test
    script:
        - ./cmake.bash Release -D MEFDN_ENABLE_MEULT=OFF -D MEDSM2_ULT_ITF=SCT
        - ./make.bash Release VERBOSE=1
        - ./ctest.bash Release -V

# CTMTH

test_ctmth_debug_job:
    stage: test
    script:
        - ./cmake.bash Debug -D MEFDN_ENABLE_MEULT=OFF -D MEDSM2_ULT_ITF=CTMTH
        - ./make.bash Debug VERBOSE=1
        - ./ctest.bash Debug -V

test_ctmth_relwithdebinfo_job:
    stage: test
    script:
        - ./cmake.bash RelWithDebInfo -D MEFDN_ENABLE_MEULT=OFF -D MEDSM2_ULT_ITF=CTMTH
        - ./make.bash RelWithDebInfo VERBOSE=1
        - ./ctest.bash RelWithDebInfo -V

test_ctmth_release_job:
    stage: test
    script:
        - ./cmake.bash Release -D MEFDN_ENABLE_MEULT=OFF -D MEDSM2_ULT_ITF=CTMTH
        - ./make.bash Release VERBOSE=1
        - ./ctest.bash Release -V

# MTH

test_mth_debug_job:
    stage: test
    script:
        - ./cmake.bash Debug -D MEFDN_ENABLE_MEULT=OFF -D MEDSM2_ULT_ITF=MTH
        - ./make.bash Debug VERBOSE=1
        - ./ctest.bash Debug -V

test_mth_relwithdebinfo_job:
    stage: test
    script:
        - ./cmake.bash RelWithDebInfo -D MEFDN_ENABLE_MEULT=OFF -D MEDSM2_ULT_ITF=MTH
        - ./make.bash RelWithDebInfo VERBOSE=1
        - ./ctest.bash RelWithDebInfo -V

test_mth_release_job:
    stage: test
    script:
        - ./cmake.bash Release -D MEFDN_ENABLE_MEULT=OFF -D MEDSM2_ULT_ITF=MTH
        - ./make.bash Release VERBOSE=1
        - ./ctest.bash Release -V

# MEULT + MTH

test_meult_mth_debug_job:
    stage: test
    script:
        - ./cmake.bash Debug
        - ./make.bash Debug VERBOSE=1
        - ./ctest.bash Debug -V

test_meult_mth_relwithdebinfo_job:
    stage: test
    script:
        - ./cmake.bash RelWithDebInfo
        - ./make.bash RelWithDebInfo VERBOSE=1
        - ./ctest.bash RelWithDebInfo -V

test_meult_mth_release_job:
    stage: test
    script:
        - ./cmake.bash Release
        - ./make.bash Release VERBOSE=1
        - ./ctest.bash Release -V

# UCT

compile_uct_debug_job:
    stage: test
    script:
        - ./cmake.bash Debug -D MEFDN_ENABLE_MEULT=OFF -D MEDSM2_RMA_ITF=UCT -D MEDSM2_ULT_ITF=SCT
        - ./make.bash Debug VERBOSE=1
        - ./cmake.bash Debug -D MEFDN_ENABLE_MEULT=OFF -D MEDSM2_RMA_ITF=UCT -D MEDSM2_ULT_ITF=CTMTH
        - ./make.bash Debug VERBOSE=1
        - ./cmake.bash Debug -D MEFDN_ENABLE_MEULT=OFF -D MEDSM2_RMA_ITF=UCT -D MEDSM2_ULT_ITF=MTH
        - ./make.bash Debug VERBOSE=1


