
#pragma once

#include <menps/meuct/common.hpp>

namespace menps {
namespace meuct {

#define MEUCT_UCT_PROXY_FUNCS_SYNC(X, ...) \
    MEDEV2_UCT_IFACE_FUNCS_SYNC_STATUS(X, __VA_ARGS__) \
    MEDEV2_UCT_EP_FUNCS_SYNC_STATUS(X, __VA_ARGS__) \

#define MEUCT_UCT_PROXY_EP_FUNCS_ASYNC(X, ...) \
    MEDEV2_UCT_EP_FUNCS_EP_FLUSH(X, __VA_ARGS__) \
    MEDEV2_UCT_EP_FUNCS_ASYNC_STATUS_IMPLICIT(X, __VA_ARGS__) \
    MEDEV2_UCT_EP_FUNCS_ASYNC_STATUS_COMPLETION(X, __VA_ARGS__) \
    MEDEV2_UCT_EP_FUNCS_ASYNC_SSIZE_T_IMPLICIT(X, __VA_ARGS__)

#define MEUCT_UCT_PROXY_FUNCS_ASYNC(X, ...) \
    MEDEV2_UCT_IFACE_FUNCS_IFACE_FLUSH(X, __VA_ARGS__) \
    MEUCT_UCT_PROXY_EP_FUNCS_ASYNC(X, __VA_ARGS__)

#define MEUCT_UCT_PROXY_FUNCS(X, ...) \
    MEUCT_UCT_PROXY_FUNCS_SYNC(X, __VA_ARGS__) \
    MEUCT_UCT_PROXY_FUNCS_ASYNC(X, __VA_ARGS__)

#define MEUCT_UCT_MANUAL_PROXY_FUNCS(X, ...) \
    MEDEV2_UCT_WORKER_FUNCS_WORKER_CREATE(X, __VA_ARGS__) \
    MEDEV2_UCT_WORKER_FUNCS_WORKER_DESTROY(X, __VA_ARGS__) \
    MEDEV2_UCT_WORKER_FUNCS_WORKER_PROGRESS(X, __VA_ARGS__) \
    MEDEV2_UCT_IFACE_FUNCS_IFACE_OPEN(X, __VA_ARGS__) \
    MEDEV2_UCT_IFACE_FUNCS_IFACE_CLOSE(X, __VA_ARGS__) \
    MEDEV2_UCT_IFACE_FUNCS_IFACE_PROGRESS(X, __VA_ARGS__) \
    MEDEV2_UCT_EP_FUNCS_EP_CREATE(X, __VA_ARGS__) \
    MEDEV2_UCT_EP_FUNCS_EP_DESTROY(X, __VA_ARGS__)

#define MEUCT_UCT_NON_PROXY_FUNCS(X, ...) \
    MEDEV2_UCT_OTHER_FUNCS_SYNC_STATUS(X, __VA_ARGS__) \
    MEDEV2_UCT_OTHER_FUNCS_SYNC_VOID(X, __VA_ARGS__)

} // namespace meuct
} // namespace menps

